# Generated by Django 5.2.5 on 2025-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easylearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('gu', 'Gujarati'), ('hi', 'Hindi')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('gu', 'Gujarati'), ('hi', 'Hindi')], default='en', max_length=2),
        ),
    ]
